### ISSUE TITLE
关于屏保

### ISSUE THREAD

**Issue by yishunzhikong** [NateLol/luci-app-oled#1]
屏保不建议使用他示例文件里面绘制的图形，示例图形点亮的像素非常多，一样会导致光衰，建议使用里面的那个五角星配合滚动函数或者直接使用滚动示例函数，这样的话好得多。

**Comment by NateLol** [comment]
OK。我添加一个滚动，然后给个自定义字符串

**Comment by NateLol** [comment]
我添加了自定义文字scroll，此issue关闭。

**Comment by NateLol** [comment]
我添加了自定义文字scroll，此issue关闭。
