### ISSUE TITLE
你好，反馈下问题

### ISSUE THREAD

**Issue by kankankankankankan** [NateLol/luci-app-oled#13]
我在勾选了
启用+IP+CPU温度+CPU频率+网速后
屏幕的IP显示有问题4位数字在变动

**Comment by NateLol** [comment]
可以给几张图吗？

**Comment by kankankankankankan** [comment]
可以的![image](https://user-images.githubusercontent.com/11487346/87767615-7ccbf600-c84d-11ea-9792-99cf08cd3dcd.png)

**Comment by NateLol** [comment]
这个是显示的是lan的ip，也就是你路由器后台的地址，相关命令是`ifconfig br-lan` 一般应该是没有问题的。

你可以ssh上去运行上面的代码，看是否出现`inet address:xxxx`，把图发出来吧。这样好判断是不是程序问题。

**Comment by kankankankankankan** [comment]
按照您所说的，方法SSH运行后正常显示

**Comment by kankankankankankan** [comment]
<img width="586" alt="截屏2020-07-17 17 05 08" src="https://user-images.githubusercontent.com/11487346/87769117-b7cf2900-c84f-11ea-97e5-2205857a871e.png">
如图

**Comment by kankankankankankan** [comment]
大概知道问题了，我在接口的LAN-物理设置-取消勾选了桥接，就出现这个情况了，如果勾选上显示没问题

**Comment by NateLol** [comment]
嗯嗯，固定读取`br-lan`，而没用`eth0` `eth1` 是考虑到有的固件会交换他们。

**Comment by kankankankankankan** [comment]
好的，感谢解答 ，那我就勾选上，辛苦你了
