### ISSUE TITLE
OLED安装后无法启动运行

### ISSUE THREAD

**Issue by nYcHockey** [NateLol/luci-app-oled#18]
是有那个依赖少装了嘛

**Comment by NateLol** [comment]
什么固件？

**Comment by nYcHockey** [comment]
> 什么固件？

nicksun88，0724的固件

**Comment by NateLol** [comment]
有可能缺内核驱动，去看issue #10，问问nick他的固件那个内核驱动有没有。

**Comment by nYcHockey** [comment]
> 有可能缺内核驱动，去看issue #10，问问nick他的固件那个内核驱动有没有。

好的，谢谢
