### ISSUE TITLE
关于网速

### ISSUE THREAD

**Issue by yishunzhikong** [NateLol/luci-app-oled#2]
网速可不可以这样，使用ifstat用
```
ifstat -i eth0 -S -t > /tmp/test
```
将实时速度输出某一文件，然后OLED程序打开该文件，读取最后一行速度值？
该文件数据就像这样：

```
  Time           eth0       
HH:MM:SS   KB/s in  KB/s out

18:17:37    537.14      7.64
18:17:38     82.99      4.64
18:17:39    546.40     13.30
18:17:40    834.86     19.00
```
只是这样得定时清理该文件，不然会越来越大。
又或者使用openwrt自带的实时速度监测方法？

**Comment by NateLol** [comment]
看起来可以！

**Comment by QiuSimons** [comment]
> 看起来可以！

eth0 or eth1可以做成可选项么，方便调换lan wan的情况

**Comment by yishunzhikong** [comment]
> 看起来可以！

但是有个问题，就是ifstat输出一定数据之后会把标题重新输出一遍，这样就需要程序里面辨别一下了

**Comment by yishunzhikong** [comment]
> 看起来可以！

或者这样，看看op网页监控速度的监控用的什么方法，用op的这个方法，更好
![image](https://user-images.githubusercontent.com/34941376/85848074-1cf8a700-b7db-11ea-9bba-26c7674b0ce7.png)

**Comment by QiuSimons** [comment]
> 网速可不可以这样，使用ifstat用
> 
> ```
> ifstat -i eth0 -S -t > /tmp/test
> ```
> 
> 将实时速度输出某一文件，然后OLED程序打开该文件，读取最后一行速度值？
> 该文件数据就像这样：
> 
> ```
>   Time           eth0       
> HH:MM:SS   KB/s in  KB/s out
> 
> 18:17:37    537.14      7.64
> 18:17:38     82.99      4.64
> 18:17:39    546.40     13.30
> 18:17:40    834.86     19.00
> ```
> 
> 只是这样得定时清理该文件，不然会越来越大。
> 又或者使用openwrt自带的实时速度监测方法？

https://stackoverflow.com/a/596960
可以看看这边的轮子

**Comment by NateLol** [comment]
> > 网速可不可以这样，使用ifstat用
> > ```
> > ifstat -i eth0 -S -t > /tmp/test
> > ```
> > 
> > 
> > 将实时速度输出某一文件，然后OLED程序打开该文件，读取最后一行速度值？
> > 该文件数据就像这样：
> > ```
> >   Time           eth0       
> > HH:MM:SS   KB/s in  KB/s out
> > 
> > 18:17:37    537.14      7.64
> > 18:17:38     82.99      4.64
> > 18:17:39    546.40     13.30
> > 18:17:40    834.86     19.00
> > ```
> > 
> > 
> > 只是这样得定时清理该文件，不然会越来越大。
> > 又或者使用openwrt自带的实时速度监测方法？
> 
> https://stackoverflow.com/a/596960
> 可以看看这边的轮子

找了个ash的轮子嵌进去了，没怎么测试，有问题再开issue
