### ISSUE TITLE
请问屏幕如何连接r2s?

### ISSUE THREAD

**Issue by chen010311** [NateLol/luci-app-oled#20]
不知道是接到gpio还是用usb转ttl？如果是gpio请问发送和接收是哪2个引脚？

**Comment by programmejava** [comment]
接gpio 淘宝上有12832点阵屏，四针vcc gnd sda scl对应接到r2s上的gpio在板背面有标示。前提是要给r2s的gpio接口焊上排针，然后用杜邦线接显示屏
![IMG_20200904_223216](https://user-images.githubusercontent.com/24750938/92251174-05d2e580-eeff-11ea-86de-3102f2c49da4.jpg)

**Comment by NateLol** [comment]
已有人回答，因此关闭此issue
