### ISSUE TITLE
用lean的源码编译的是英文界面，不能切换成汉语，请问是什么原因

### ISSUE THREAD

**Issue by hanlihanshaobo** [NateLol/luci-app-oled#21]

**Comment by NateLol** [comment]
可以给出具体的lean版本吗？或者github连接?有可能是语言文件的文件夹定义zh_cn和zh_hans之间的差异把

**Comment by hanlihanshaobo** [comment]
> 可以指定具体的lean版本吗？或者github连接？有可能是语言文件的文件夹定义zh_cn和zh_hans之间的差异把

https://github.com/coolsnowwolf/lede 感谢

**Comment by NateLol** [comment]
把po文件夹下的zh_Hans文件夹名字改成zh-cn试一试 应该是可以的了

**Comment by NateLol** [comment]
注意是zh_Hans变成zh-cn 一个是下划线一个是连字符

**Comment by hanlihanshaobo** [comment]
> 注意是zh_Hans变成zh-cn 一个是下划线一个是连字符

好的，谢谢

**Comment by NateLol** [comment]
Closure of the issue.
