### ISSUE TITLE
(请求帮助)请问有没有焊接教程

### ISSUE THREAD

**Issue by CodeWithMyLife** [NateLol/luci-app-oled#23]
请问如何焊接，以及改购买什么类型的显示屏，麻烦详细推荐一下，谢谢 啦~

**Comment by endou007** [comment]
同样需求，顶一下。

**Comment by endou007** [comment]
淘宝链接如下：
3👈 ha:/哈BCdlXTsGSzs，  0.91寸oled显示屏128x32白光OLED液晶屏模块IIC高清高亮宽视角

忘告知焊接方法，谢谢

**Comment by CodeWithMyLife** [comment]
已经焊接好，可以Closed了

[<a href="https://sm.ms/image/ePYlwSHE7QoLWTX" target="_blank"><img src="https://i.loli.net/2021/06/10/ePYlwSHE7QoLWTX.png" ></a>](url)

**Comment by endou007** [comment]
> 已经焊接好，可以Closed了

请教一下教程后再Close吧。

**Comment by CodeWithMyLife** [comment]
> > 已经焊接好，可以Closed了
> 
> 请教一下教程后再Close吧。

板子上有对应的焊接点，在灯的旁边，一一对应焊接就可以了，推荐5v

**Comment by endou007** [comment]
是用的4针对4槽的那一竖条焊接点吗？

**Comment by CodeWithMyLife** [comment]
> 是用的4针对4槽的那一竖条焊接点吗？

一一对应就好了呗，我是直接焊死了

**Comment by endou007** [comment]
方便把焊点的图发一个给我看看吗？
还有，你的oled模块是上面我提供淘宝的链接购买的吗？

**Comment by NateLol** [comment]
Closing this as it has been silent for a while.
