### ISSUE TITLE
How to install this app to openwrt ?

### ISSUE THREAD

**Issue by yoyojacky** [NateLol/luci-app-oled#24]
Hi，I have try to unzip this repo to  ~/openwrt/feeds/luci/application/luci-app-oled and removed  ~/openwrt/tmp folder, also i have already update feeds by  following commands:
```bash
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig
```
Navigate to `Luci` ---> `application`----> but i can not find the selection `luci-app-oled`, how can i correct this issue? 
or could you please show me how to add this app to openwrt ?

**Comment by NateLol** [comment]
Maybe you can try clone this repo under the `package` folder which contains `lean` if you are using it.

Run `make manuconfig`, you shall be able to find it under `luci` -> `application` -> `luci-app-oled`.

I am not sure whether this can be installed on the fly but you can find compiled ipk from releases in this repo. After you upload to openwrt, try `opkg install xxxx.ipk`, you might run into missing dependencies as this oled depends on i2c driver as i can remember.

Good luck with it!

**Comment by yoyojacky** [comment]
> run int

Hi NateLol, 
Thanks for your reply, and i am using the latest clone of OpenWRT source  from github, and i have already check the I2C kmod , i2c bus and so on in  kernel modules,  and i have already copy this `luci-app-oled` under the folder `openwrt/feeds/luci/application/luci-app-oled`,  and also execute following command as well: 
```
./scripts/feeds update -a 
./scripts/feeds install -a
```
but in `make menuconfig` ---> `luCI` ---> `Applications`---> there  not `luci-app-oled` appears in the menu, so i am confused by this result, should i modify other file ? 
I am using a Raspberry Pi 4B device to compile a 64bit Openwrt firmware, but still no luck ...
but thanks for your reply again, i will try it again.

**Comment by NateLol** [comment]
Good to know that you've solved it and thanks for posting the detailed process which would benefit others in the future.

**Comment by yoyojacky** [comment]
> Good to know that you've solved it and thanks for posting the detailed process which would benefit others in the future.

you are welcome~ this is a nice app, I love it very much~
