### ISSUE TITLE
关于显示大小。

### ISSUE THREAD

**Issue by GIT-POPO** [NateLol/luci-app-oled#3]
希望当勾选单项时。内容的字体，能和屏保一样大，且只显示数字和后面单位即可。

**Comment by NateLol** [comment]
可以实现和屏保一样大，但有2个前提：
1. 显示总长度不可以超过10个字符
2. 实时更新的信息，如温度，不可以滚动显示，只能固定。

**Comment by GIT-POPO** [comment]
> 可以实现和屏保一样大，但有2个预设：
> 
> 1. 显示总长度不可以超过10个字符
> 2. 实时更新的信息，如温度，不可以滚动显示，只能固定。

对的，当√选单项的时候，前面的项目名称都去掉，只显示数字和后面的单位。这样就不会超过10个字符。

**Comment by yishunzhikong** [comment]
> 可以实现和屏保一样大，但有2个前提：
> 
> 1. 显示总长度不可以超过10个字符
> 2. 实时更新的信息，如温度，不可以滚动显示，只能固定。

他的意思是类似这种
![image](https://user-images.githubusercontent.com/34941376/85921646-20119700-b8b0-11ea-8c79-ac390b02d9ce.png)
![image](https://user-images.githubusercontent.com/34941376/85921651-2869d200-b8b0-11ea-9364-b1450bbea39c.png)

**Comment by NateLol** [comment]
已经更新，关闭此issue。
