### ISSUE TITLE
求大佬出手移植到armbian

### ISSUE THREAD

**Issue by 100001000** [NateLol/luci-app-oled#4]
由于r2s只是拿来做旁路用，用不到openwrt 屏幕太浪费了，不知道可否求大佬友情出手移植到armbian😂，实在不行的话点亮屏幕显示个时间也行吖（小白厚脸皮卖萌😊）

**Comment by NateLol** [comment]
我没玩过armbian，不过应该在[src文件夹](https://github.com/NateLol/luci-app-oled/tree/master/src)下make oled一下出来的就可以用了。

因为我写的比较随意，使用方法可以看[这里](https://github.com/NateLol/luci-app-oled/blob/7f7ac09411e926bb05aa9356116b38f5fc96171c/root/etc/init.d/oled#L43)
`nohup oled ${date} ${lanip} ${cputemp} ${cpufreq} ${netspeed} ${time} ${drawline} ${drawrect} ${fillrect} ${drawcircle} ${drawroundrect} ${fillroundrect} ${drawtriangle} ${filltriangle} ${displaybitmap} ${displayinvertnormal}  ${drawbitmapeg} ${scroll} "${text}"> /dev/null 2>&1 &
`
每个代表一个设置（0或者1）.
netspeed不可用，其他都可以设置

例如 只显示时间加滚动屏保（内容为”nanopi r2s“每60秒切换一次）。
`nohup oled 1 0 0 0 0 60 0 0 0 0 0 0 0 0 0 0 0 1 "nanopi r2s"> /devs/null 2>&1 &`

只能帮你到这里了。

**Comment by NateLol** [comment]
可以去这里看看，，应该可以在armbian上面运行的。
[SSD1306_OLED_json](https://github.com/yishunzhikong/SSD1306_OLED_json/releases)
> 由于r2s只是拿来做旁路用，用不到openwrt 屏幕太浪费了，不知道可否求大佬友情出手移植到armbian😂，实在不行的话点亮屏幕显示个时间也行吖（小白厚脸皮卖萌😊）
