### ISSUE TITLE
计划任务运行时会发生闪烁

### ISSUE THREAD

**Issue by gyj1109** [NateLol/luci-app-oled#8]
闪烁很引人注意，能不能只卡一下而不让屏幕关闭？

**Comment by gyj1109** [comment]
顺便一问，这个crontab是什么作用？为什么要重启？

**Comment by NateLol** [comment]
因为测试发现长时间运行之后，系统中好像有内存泄漏，暂改成定时重启。

**Comment by gyj1109** [comment]
https://github.com/NateLol/luci-app-oled/pull/12 可以在restart时不发生闪烁，稍微缓解一下这个问题。
但根本上的内存泄漏问题似乎是OpenWrt的，我自己实现的OLED程序也这样
以后有办法再解决吧
